name: energy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  # rive: ^0.10.0
  glassmorphism: ^3.0.0
  font_awesome_flutter: ^10.3.0
  reorderableitemsview: ^2.0.1
  syncfusion_flutter_charts: ^20.4.38
  lottie: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_app_name: ^0.1.1
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter

flutter_app_name:
  name: "Eneloop"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/energy/
    - assets/splash/
    - assets/logo/
    - assets/lottie/
